version: '3.8'

services:
  # BACKEND
  backend:
    container_name: backend
    image: backend:1.0.0
    build:
      context: backend
      dockerfile: dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app
    depends_on:
      - frontend
  # FRONTEND
  frontend:
    container_name: frontend
    image: frontend:1.0.0
    build:
      context: frontend
      dockerfile: dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app